# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dfs.proto',
  package='dfs',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tdfs.proto\x12\x03\x64\x66s\"\x16\n\x07\x43hunkId\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\")\n\x0cWriteRequest\x12\x0b\n\x03\x63id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1d\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"p\n\x0eSegmentRequest\x12\x0b\n\x03sid\x18\x01 \x01(\t\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\t\x12\x10\n\x08parities\x18\x03 \x03(\t\x12\x16\n\x0e\x63hunk_location\x18\x04 \x03(\t\x12\x17\n\x0fparity_location\x18\x05 \x03(\t\"\x8b\x01\n\tChunkList\x12$\n\x03map\x18\x01 \x03(\x0b\x32\x17.dfs.ChunkList.MapEntry\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\t\x12\x0b\n\x03\x63\x66t\x18\x03 \x01(\x05\x1a;\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.dfs.StringList:\x02\x38\x01\"\x1a\n\nStringList\x12\x0c\n\x04strs\x18\x01 \x03(\t\"\x15\n\x06Number\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x15\n\x05\x42ytes\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x15\n\x06String\x12\x0b\n\x03str\x18\x01 \x01(\t\"\x16\n\x04\x42ool\x12\x0e\n\x06verify\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\xa5\x01\n\x0b\x43hunkServer\x12 \n\x04Read\x12\x0c.dfs.ChunkId\x1a\n.dfs.Bytes\x12&\n\x05Write\x12\x11.dfs.WriteRequest\x1a\n.dfs.Empty\x12\"\n\x06\x44\x65lete\x12\x0c.dfs.ChunkId\x1a\n.dfs.Empty\x12(\n\tGetChunks\x12\n.dfs.Empty\x1a\x0f.dfs.StringList2\xe9\x01\n\x0cMasterServer\x12\x30\n\x0cRegisterPeer\x12\x14.dfs.RegisterRequest\x1a\n.dfs.Empty\x12&\n\x07GetFile\x12\x0b.dfs.String\x1a\x0e.dfs.ChunkList\x12&\n\nDeleteFile\x12\x0b.dfs.String\x1a\x0b.dfs.String\x12(\n\x08GetPeers\x12\x0b.dfs.Number\x1a\x0f.dfs.StringList\x12-\n\nAddSegment\x12\x13.dfs.SegmentRequest\x1a\n.dfs.Emptyb\x06proto3'
)




_CHUNKID = _descriptor.Descriptor(
  name='ChunkId',
  full_name='dfs.ChunkId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='dfs.ChunkId.cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=40,
)


_WRITEREQUEST = _descriptor.Descriptor(
  name='WriteRequest',
  full_name='dfs.WriteRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cid', full_name='dfs.WriteRequest.cid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='dfs.WriteRequest.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=83,
)


_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='dfs.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='dfs.RegisterRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=114,
)


_SEGMENTREQUEST = _descriptor.Descriptor(
  name='SegmentRequest',
  full_name='dfs.SegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='dfs.SegmentRequest.sid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='dfs.SegmentRequest.chunks', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parities', full_name='dfs.SegmentRequest.parities', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunk_location', full_name='dfs.SegmentRequest.chunk_location', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parity_location', full_name='dfs.SegmentRequest.parity_location', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=228,
)


_CHUNKLIST_MAPENTRY = _descriptor.Descriptor(
  name='MapEntry',
  full_name='dfs.ChunkList.MapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='dfs.ChunkList.MapEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='dfs.ChunkList.MapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=370,
)

_CHUNKLIST = _descriptor.Descriptor(
  name='ChunkList',
  full_name='dfs.ChunkList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map', full_name='dfs.ChunkList.map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chunks', full_name='dfs.ChunkList.chunks', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cft', full_name='dfs.ChunkList.cft', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CHUNKLIST_MAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=370,
)


_STRINGLIST = _descriptor.Descriptor(
  name='StringList',
  full_name='dfs.StringList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='strs', full_name='dfs.StringList.strs', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=398,
)


_NUMBER = _descriptor.Descriptor(
  name='Number',
  full_name='dfs.Number',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='dfs.Number.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=421,
)


_BYTES = _descriptor.Descriptor(
  name='Bytes',
  full_name='dfs.Bytes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='dfs.Bytes.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=444,
)


_STRING = _descriptor.Descriptor(
  name='String',
  full_name='dfs.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='dfs.String.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=467,
)


_BOOL = _descriptor.Descriptor(
  name='Bool',
  full_name='dfs.Bool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='verify', full_name='dfs.Bool.verify', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=491,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='dfs.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=500,
)

_CHUNKLIST_MAPENTRY.fields_by_name['value'].message_type = _STRINGLIST
_CHUNKLIST_MAPENTRY.containing_type = _CHUNKLIST
_CHUNKLIST.fields_by_name['map'].message_type = _CHUNKLIST_MAPENTRY
DESCRIPTOR.message_types_by_name['ChunkId'] = _CHUNKID
DESCRIPTOR.message_types_by_name['WriteRequest'] = _WRITEREQUEST
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['SegmentRequest'] = _SEGMENTREQUEST
DESCRIPTOR.message_types_by_name['ChunkList'] = _CHUNKLIST
DESCRIPTOR.message_types_by_name['StringList'] = _STRINGLIST
DESCRIPTOR.message_types_by_name['Number'] = _NUMBER
DESCRIPTOR.message_types_by_name['Bytes'] = _BYTES
DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Bool'] = _BOOL
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChunkId = _reflection.GeneratedProtocolMessageType('ChunkId', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKID,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.ChunkId)
  })
_sym_db.RegisterMessage(ChunkId)

WriteRequest = _reflection.GeneratedProtocolMessageType('WriteRequest', (_message.Message,), {
  'DESCRIPTOR' : _WRITEREQUEST,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.WriteRequest)
  })
_sym_db.RegisterMessage(WriteRequest)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

SegmentRequest = _reflection.GeneratedProtocolMessageType('SegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTREQUEST,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.SegmentRequest)
  })
_sym_db.RegisterMessage(SegmentRequest)

ChunkList = _reflection.GeneratedProtocolMessageType('ChunkList', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _CHUNKLIST_MAPENTRY,
    '__module__' : 'dfs_pb2'
    # @@protoc_insertion_point(class_scope:dfs.ChunkList.MapEntry)
    })
  ,
  'DESCRIPTOR' : _CHUNKLIST,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.ChunkList)
  })
_sym_db.RegisterMessage(ChunkList)
_sym_db.RegisterMessage(ChunkList.MapEntry)

StringList = _reflection.GeneratedProtocolMessageType('StringList', (_message.Message,), {
  'DESCRIPTOR' : _STRINGLIST,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.StringList)
  })
_sym_db.RegisterMessage(StringList)

Number = _reflection.GeneratedProtocolMessageType('Number', (_message.Message,), {
  'DESCRIPTOR' : _NUMBER,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.Number)
  })
_sym_db.RegisterMessage(Number)

Bytes = _reflection.GeneratedProtocolMessageType('Bytes', (_message.Message,), {
  'DESCRIPTOR' : _BYTES,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.Bytes)
  })
_sym_db.RegisterMessage(Bytes)

String = _reflection.GeneratedProtocolMessageType('String', (_message.Message,), {
  'DESCRIPTOR' : _STRING,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.String)
  })
_sym_db.RegisterMessage(String)

Bool = _reflection.GeneratedProtocolMessageType('Bool', (_message.Message,), {
  'DESCRIPTOR' : _BOOL,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.Bool)
  })
_sym_db.RegisterMessage(Bool)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'dfs_pb2'
  # @@protoc_insertion_point(class_scope:dfs.Empty)
  })
_sym_db.RegisterMessage(Empty)


_CHUNKLIST_MAPENTRY._options = None

_CHUNKSERVER = _descriptor.ServiceDescriptor(
  name='ChunkServer',
  full_name='dfs.ChunkServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=503,
  serialized_end=668,
  methods=[
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='dfs.ChunkServer.Read',
    index=0,
    containing_service=None,
    input_type=_CHUNKID,
    output_type=_BYTES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='dfs.ChunkServer.Write',
    index=1,
    containing_service=None,
    input_type=_WRITEREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='dfs.ChunkServer.Delete',
    index=2,
    containing_service=None,
    input_type=_CHUNKID,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetChunks',
    full_name='dfs.ChunkServer.GetChunks',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STRINGLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CHUNKSERVER)

DESCRIPTOR.services_by_name['ChunkServer'] = _CHUNKSERVER


_MASTERSERVER = _descriptor.ServiceDescriptor(
  name='MasterServer',
  full_name='dfs.MasterServer',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=671,
  serialized_end=904,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterPeer',
    full_name='dfs.MasterServer.RegisterPeer',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetFile',
    full_name='dfs.MasterServer.GetFile',
    index=1,
    containing_service=None,
    input_type=_STRING,
    output_type=_CHUNKLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteFile',
    full_name='dfs.MasterServer.DeleteFile',
    index=2,
    containing_service=None,
    input_type=_STRING,
    output_type=_STRING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetPeers',
    full_name='dfs.MasterServer.GetPeers',
    index=3,
    containing_service=None,
    input_type=_NUMBER,
    output_type=_STRINGLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddSegment',
    full_name='dfs.MasterServer.AddSegment',
    index=4,
    containing_service=None,
    input_type=_SEGMENTREQUEST,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MASTERSERVER)

DESCRIPTOR.services_by_name['MasterServer'] = _MASTERSERVER

# @@protoc_insertion_point(module_scope)
